var menuData = [{
    id: '100',
    text: '入场煤管理',
    icon: 'icon-truck',
    url: '/hcm/rcmQuery',
    'class': 'hidden'
}, {
    id: '200',
    text: '火车煤管理',
    icon: 'glyphicon glyphicon-road',
    url: '',
    'class': 'hidden',
    menus: [{
        id: '210',
        text: '调度查询',
        //icon: 'glyphicon glyphicon-sort',
        icon: 'icon-glass',
        'class': 'hidden',
        url: '/hcm/ddtrainquery',
    }, {
        id: '220',
        'class': 'hidden',
        text: '火车煤查询',
        icon: 'icon-glass',
        url: '/hcm/hcmQuery'
    },
        {
        id: '230',
        text: '火车煤编码',
        'class': 'hidden',
        icon: 'icon-glass',
        url: '/hcm/hcmCode'
    },  {
        id: '240',
        text: '火车采样通知单',
        'class': 'hidden',
        icon: 'icon-glass',
        url: '/hcm/getCynotice'
    }, {
        id: '250',
        text: '火车采样报告单',
        'class': 'hidden',
        icon: 'icon-glass',
        url: '/Report/index'
    }]
}, {
    id: '300',
    text: '水运煤管理',
    icon: 'icon-align-center',
    url: '',
    'class': 'hidden',
    menus: [
         {
            id: '310',
            'class': 'hidden',
            text: '水运煤查询',
            icon: 'icon-glass',
            url: '/sym/symQuery'
        },
        {
        id: '320',
        text: '水运煤编码',
        'class': 'hidden',
        icon: 'icon-glass',
        url: '/sym/symCode'
    }, {
        id: '330',
        text: '水运采样通知单',
        'class': 'hidden',
        icon: 'icon-glass',
        url: '/sym/getCynotice'
    }, {
        id: '340',
        text: '水运采样报告单',
        'class': 'hidden',
        icon: 'icon-glass',
        url: '/SymReport/index'
    }]
}, {
    id: '350',
    text: '入炉煤管理',
    icon: 'glyphicon glyphicon-tower',
    url: '/rlm/rlmQuery',
    'class': 'hidden'    
},
{
    id: '400',
    text: '皮带秤管理',
    icon: 'icon-th-list',
    'class': 'hidden',
    url: '',
    menus: [{
        id: '410',
        text: '皮带秤查询',
        icon: 'icon-glass',
        url: '/pdc/pdcQuery',
        'class': 'hidden'
    }]
},
{
    id: '500',
    text: '采样管理',
    icon: 'icon-tint',
    'class': 'hidden',
    url: '',
    menus: [{
        id: '510',
        text: '火车采样查询',
        icon: 'icon-glass',
        'class': 'hidden',
        url: '/cy/hccyquery'
    }, {
        id: '520',
        text: '船运采样查询',
        icon: 'icon-glass',
        'class': 'hidden',
        url: '/cy/cycyquery'
    }, {
        id: '530',
        text: '入炉采样查询',
        'class': 'hidden',
        icon: 'icon-glass',
        url: '/cy/rlcyquery'
    }, {
        id: '531',
        text: '翻车机信息查询',
        icon: 'icon-glass',
        'class': 'hidden',
        url: '/cy/fcjquery'
    }, {
        id: '540',
        text: '采样机操作查询',
        icon: 'icon-glass',
        'class': 'hidden',
        url: '/cy/cycommandquery'
    }, {
        id: '550',
        text: '采样机报警查询',
        icon: 'icon-glass',
        'class': 'hidden',
        url: '/cy/cyalarmquery'
    }, {
        id: '560',
        text: '采样机运行查询',
        icon: 'icon-glass',
        'class': 'hidden',
        url: '/cy/cylogquery'
    }]
},
{
    id: '600',
    text: '封装打包管理',
    icon: 'icon-credit-card',
    'class': 'hidden',
    url: '',
    menus: [{
        id: '601',
        text: '封装打包主表查询',
        icon: 'icon-glass',
        url: '/fzdb/fzdbQuery',
        'class': 'hidden'
    }, {
        id: '602',
        text: '封装打包样桶实时信息表查询',
        icon: 'icon-glass',
        url: '/fzdb/fzdbBarrelStateQuery',
        'class': 'hidden'
    }, {
        id: '603',
        text: '封装打包打包样桶记录表查询',
        icon: 'icon-glass',
        url: '/fzdb/fzdbBarrelRecordQuery',
        'class': 'hidden'
    }, {
        id: '604',
        text: '封装打包数据表查询',
        icon: 'icon-glass',
        url: '/fzdb/fzdbDeviceQuery',
        'class': 'hidden'
    }, {
        id: '605',
        text: '封装打包信息表查询',
        icon: 'icon-glass',
        url: '/fzdb/fzdbFzInfoQuery',
        'class': 'hidden'
    }, {
        id: '606',
        text: '封装打包命令表查询',
        icon: 'icon-glass',
        url: '/fzdb/fzdbFzCommandQuery',
        'class': 'hidden'
    }, {
        id: '607',
        text: '封装打包报警表查询',
        icon: 'icon-glass',
        url: '/fzdb/fzdbFzAlarmQuery',
        'class': 'hidden'
    }, {
        id: '608',
        text: '封装打包设备总体状态查询',
        icon: 'icon-glass',
        url: '/fzdb/fzdbFzStateQuery',
        'class': 'hidden'
    }, {
        id: '609',
        text: '封装打包设备状态子表查询',
        icon: 'icon-glass',
        url: '/fzdb/fzdbFzDeviceStateQuery',
        'class': 'hidden'
    }, {
        id: '610',
        text: '封装打包分选信息表查询',
        icon: 'icon-glass',
        url: '/fzdb/fzdbFxInfoQuery',
        'class': 'hidden'
    }, {
        id: '611',
        text: '封装打包分选命令表查询',
        icon: 'icon-glass',
        url: '/fzdb/fzdbFxCommandQuery',
        'class': 'hidden'
    }, {
        id: '612',
        text: '封装打包分选报警表查询',
        icon: 'icon-glass',
        url: '/fzdb/fzdbFxAlarmQuery',
        'class': 'hidden'
    }, {
        id: '613',
        text: '封装打包分选设备总体状态查询',
        icon: 'icon-glass',
        url: '/fzdb/fzdbFxStateQuery',
        'class': 'hidden'
    }, {
        id: '614',
        text: '封装打包分选设备状态子表查询',
        icon: 'icon-glass',
        url: '/fzdb/fzdbFxDeviceStateQuery',
        'class': 'hidden'
    }, {
        id: '615',
        text: '封装打包分选暂存信息表查询',
        icon: 'icon-glass',
        url: '/fzdb/fzdbFxStoveQuery',
        'class': 'hidden'
    }]
},
{
    id: '700',
    text: '制样管理',
    'class': 'hidden',
    icon: 'icon-legal',
    url: '',
    menus: [{
        id: '710',
        text: '制样查询',
        'class': 'hidden',
        icon: 'icon-glass',
        url: '/zy/zymainquery'
    }, {
        id: '720',
        text: '制样信息查询',
        icon: 'icon-glass',
        'class': 'hidden',
        url: '/zy/zydetailquery'
    }, {
        id: '730',
        text: '制样机状态查询',
        icon: 'icon-glass',
        'class': 'hidden',
        url: '/zy/zydevicestatequery'
    }, {
        id: '740',
        text: '制样操作查询',
        'class': 'hidden',
        icon: 'icon-glass',
        url: '/zy/zyoperatequery'
    }, {
        id: '750',
        text: '制样报警查询',
        'class': 'hidden',
        icon: 'icon-glass',
        url: '/zy/zyalarmquery'
    }, {
        id: '760',
        text: '制样报告单查询',
        'class': 'hidden',
        icon: 'icon-glass',
        url: '/ZyReport/index'
    }]
}, {
    id: '800',
    text: '存查样柜',
    icon: 'icon-suitcase',
    'class': 'hidden',
    url: '',
    menus: [{
        id: '810',
        text: '仓位查询',
        icon: 'icon-glass',
        'class': 'hidden',
        url: '/cxyg/ccystovequery'
    }, {
        id: '811',
        text: '存查样日志查询',
        icon: 'icon-glass',
        'class': 'hidden',
        url: '/cxyg/ccyoperatelogquery'
    }, {
        id: '820',
        text: '存查样操作查询',
        icon: 'icon-glass',
        'class': 'hidden',
        url: '/cxyg/ccycommand'
    }, {
        id: '830',
        text: '存查样设备状态',
        icon: 'icon-glass',
        'class': 'hidden',
        url: '/cxyg/ccydevicestatequery'
    }, {
        id: '840',
        text: '存查样报警查询',
        icon: 'icon-glass',
        'class': 'hidden',
        url: '/cxyg/ccyalarmquery'
    }, {
        id: '850',
        text: '复查样信息查询',
        icon: 'icon-glass',
        'class': 'hidden',
        url: '/cxyg/ccyfcydetailquery'
    }]
}, {
    id: '860',
    text: '气动传输',
    icon: 'icon-retweet',
    'class': 'hidden',
    url: '',
    menus: [{
        id: '861',
        text: '气动传输总体状态查询',
        icon: 'icon-glass',
        'class': 'hidden',
        url: '/qdcs/qdcsstatequery'
    }, {
        id: '862',
        text: '气动传输设备状态查询',
        icon: 'icon-glass',
        'class': 'hidden',
        url: '/qdcs/qdcsdevicestatequery'
    }, {
        id: '863',
        text: '气动传输设备故障报警查询',
        icon: 'icon-glass',
        'class': 'hidden',
        url: '/qdcs/qdcsdevicealarmquery'
    }, {
        id: '864',
        text: '气动传输错误信息查询',
        icon: 'icon-glass',
        'class': 'hidden',
        url: '/qdcs/qdcserrinfoquery'
    }, {
        id: '865',
        text: '气动传输报警信息查询',
        icon: 'icon-glass',
        'class': 'hidden',
        url: '/qdcs/qdcswarninginfoquery'
    }, {
        id: '866',
        text: '气动传输操作记录查询',
        icon: 'icon-glass',
        'class': 'hidden',
        url: '/qdcs/qdcsoprrecordquery'
    }]
}, {
    id: '900',
    text: '化验管理',
    'class': 'hidden',
    icon: 'icon-magic',
    url: '',
    menus: [{
        id: '901',
        text: '化验数据查询',
        icon: 'icon-glass',
        'class': 'hidden',
        url: '/assay/assayquery'
    }, {
        id: '902',
        text: '化验室总体状态查询',
        'class': 'hidden',
        icon: 'icon-glass',
        url: '/assay/assaysquery'
    }, {
        id: '903',
        text: '化验设备状态查询',
        'class': 'hidden',
        icon: 'icon-glass',
        url: '/assay/assaydsquery'
    }, {
        id: '904',
        text: '化验发热量查询',
        'class': 'hidden',
        icon: 'icon-glass',
        url: '/assay/assaylrquery'
    }, {
        id: '905',
        text: '化验全水查询',
        'class': 'hidden',
        icon: 'icon-glass',
        url: '/assay/assayqsquery'
    }, {
        id: '906',
        text: '化验测硫查询',
        'class': 'hidden',
        icon: 'icon-glass',
        url: '/assay/assayclquery'
    }, {
        id: '907',
        text: '化验工业分析查询',
        'class': 'hidden',
        icon: 'icon-glass',
        url: '/assay/assaygfquery'
    }, {
        id: '908',
        text: '化验内水查询',
        'class': 'hidden',
        icon: 'icon-glass',
        url: '/assay/assaymadquery'
    }, {
        id: '909',
        text: '化验灰分查询',
        'class': 'hidden',
        icon: 'icon-glass',
        url: '/assay/assayaadquery'
    }, {
        id: '910',
        text: '化验挥发分查询',
        'class': 'hidden',
        icon: 'icon-glass',
        url: '/assay/assayvadquery'
    }, {
        id: '911',
        text: '化验氢值查询',
        'class': 'hidden',
        icon: 'icon-glass',
        url: '/assay/assaycqquery'
    }, {
        id: '912',
        text: '化验灰熔点查询',
        'class': 'hidden',
        icon: 'icon-glass',
        url: '/assay/assayhrquery'
    }]
}, {
    id: '1000',
    text: '视频门禁管理',
    'class': 'hidden',
    icon: 'icon-camera',
    url: '',
    menus: [{
        id: '1100',
        text: '门禁用户查询',
        icon: 'icon-glass',
        'class': 'hidden',
        url: '/mj/mjxtuserquery'
    }, {
        id: '1200',
        text: '门禁设备查询',
        icon: 'icon-glass',
        'class': 'hidden',
        url: '/mj/mjxtdevicequery'
    }, {
        id: '1300',
        text: '门禁记录查询',
        icon: 'icon-glass',
        'class': 'hidden',
        url: '/mj/mjxtrecordquery'
    }, {
        id: '1400',
        text: '门禁出入记录',
        icon: 'icon-glass',
        'class': 'hidden',
        url: '/mj/mjxttempquery'
    }]
}, 
{
    id: '10000',
    text: '权限管理',
    icon: 'glyphicon glyphicon-lock',
    'class': 'hidden',
    menus: [{
        id: '11000',
        text: '角色管理',
        icon: 'icon-glass',
        url: '/role/roleList',
        'class': 'hidden'
    }, {
        id: '12000',
        text: '菜单管理',
        icon: 'icon-glass',
        url: '/menu/menuList',
        'class': 'hidden'
    }, {
        id: '13000',
        text: '用户管理',
        icon: 'icon-glass',
        url: '/User/UserList',
        'class': 'hidden'
    }]
},
{
    id: '20000',
    text: '设备管理',
    icon: 'icon-th-large',
    'class': 'hidden',
    url: '',
    menus: [{
        id: '21000',
        text: '设备类型管理',
        icon: 'icon-glass',
        'class': 'hidden',
        url: '/device/devicetype',
    }, {
        id: '22000',
        text: '设备管理',
        icon: 'icon-glass',
        'class': 'hidden',
        url: '/device/deviceinfo',
    }, {
    //    id: '23000',
    //    text: '设备定期工作查询',
    //    icon: 'icon-glass',
    //    url: '/device/deviceworkrecordquery',
    //    'class': 'hidden',
    //}, {
        id: '24000',
        text: '缺陷管理',
        icon: 'icon-glass',
        url: '',
        'class': 'hidden',
        menus: [{
            id: '24100',
            text: '缺陷录入',
            icon: 'icon-glass',
            'class': 'hidden',
            url: '/device/devicemaintenance',
        }, {
            id: '24200',
            text: '缺陷查询',
            'class': 'hidden',
            icon: 'icon-glass',
            url: '/device/devicemaintenancequery',
        }]
    }, {
        id: '25000',
        text: '统计查询',
        icon: 'icon-glass',
        'class': 'hidden',
        url: '/device/devicestatquery',
    }
    ]
},
{
    id: '30000',
    text: '任务中心',
    icon: 'icon-edit',
    'class': 'hidden',
    menus: [{
        id: '31000',
        text: '任务中心',
        icon: 'icon-glass',
        url: '/work/workquery',
        'class': 'hidden'
    }, {
        id: '32000',
        text: '定期任务类型',
        icon: 'icon-glass',
        url: '/work/timeworktype',
        'class': 'hidden'
    }, {
        id: '33000',
        text: '定期任务查询',
        icon: 'icon-glass',
        url: '/work/timework',
        'class': 'hidden'
    }, {
        id: '33001',
        text: '我的未完成任务',
        icon: 'icon-glass',
        url: '/work/myWorkquery',
        'class': 'hidden'
    }, {
        id: '33002',
        text: '我的发布任务',
        icon: 'icon-glass',
        url: '/work/myPublishworkquery',
        'class': 'hidden'
    }]
},
 {
    id: '40000',
    text: '员工信息',
    icon: 'glyphicon glyphicon-user',
    url: '/SYS_EMPLOYEE/Index',
    'class': 'hidden'
 },{
    id: '50000',
    text: '文档资料',
    icon: 'icon-folder-open',
    'class': 'hidden',
    menus: [
    {
        id: '51000',
        text: '文档类型',
        icon: 'icon-glass',
        url: '/file/filetype',
        'class': 'hidden'
    }]
}, {
    id: '60000',
    text: '物资管理',
    icon: 'icon-sitemap',
    'class': 'hidden',
    url: '',
    menus: [{
        id: '61000',
        text: '物资信息',
        icon: 'icon-glass',
        url: '/goods/goodsList',
        'class': 'hidden'
    }, {
        id: '62000',
        text: '物资登记',
        icon: 'icon-glass',
        url: '/goods/goodsInfo',
        'class': 'hidden'
    }]
}, {
    id: '70000',
    text: 'GPS',
    icon: 'icon-pushpin',
    'class': 'hidden',
    url: '',
    menus: [{
        id: '71000',
        text: 'GPS实时',
        icon: 'icon-glass',
        url: '/gps/gpslocus',
        'class': 'hidden'
    }, {
        id: '72000',
        text: 'GPS历史',
        icon: 'icon-glass',
        url: '/gps/gpsrecord',
        'class': 'hidden'
    }]
}, {
    id: '80000',
    text: '动作标准化',
    icon: 'icon-play',
    'class': 'hidden',
    url: '',
    menus: [{
        id: '80001',
        text: '动作信息查询',
        icon: 'icon-glass',
        url: '/action/actionquery',
        'class': 'hidden'
    },{
        id: '80002',
        text: '动作名称查询',
        icon: 'icon-glass',
        url: '/action/actionlist',
        'class': 'hidden'
    }]
}];