//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMHJJService.Model.FMHJJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_UserInfo
    {
        public int ID { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<int> UserLvl { get; set; }
        public Nullable<int> ProductType { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> Sex { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyPhone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Mail { get; set; }
        public Nullable<int> State { get; set; }
    }
}
