//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMHJJService.Model.FMHJJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dict_FunctionMenu
    {
        public int ID { get; set; }
        public Nullable<int> PID { get; set; }
        public string FunctionName { get; set; }
        public Nullable<int> UserType { get; set; }
        public string Icon { get; set; }
        public string Url { get; set; }
    }
}
